config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  resource :dashboard, only: [:show]
  resources :groups, only: [:new, :create, :show] do
    resources :locations, only: [:new, :create, :show, :update]
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :group_memberships
  has_many :members, through: :group_memberships
  has_many :locations
end

app/models/group_membership.rb
class GroupMembership < ActiveRecord::Base
  belongs_to :group
  belongs_to :member, class_name: "User"
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :group_memberships, foreign_key: :member_id
  has_many :groups, through: :group_memberships

  def join(group)
    groups << group
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  before_filter :require_login
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @groups = current_user.groups
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def show
    @group = Group.find(params[:id])
    @members = @group.members
  end

  def new
    @group = Group.new
  end

  def create
    group = Group.create(group_params)
    current_user.join(group)
    redirect_to group
  end

  private

  def group_params
    params.require(:group).permit(:title)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def new
    @group = find_group
    @location = Location.new
  end

  def show
    @group = find_group
    @location = find_group_location(@group)
  end

  def create
    @group = find_group
    @group.locations.create(location_params)
    redirect_to @group
  end

  def update
    @group = find_group
    @location = find_group_location(@group)
    @location.update(location_params)
    redirect_to @group
  end

  private

  def find_group
    Group.find(params[:group_id])
  end

  def find_group_location(group)
    group.locations.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:name, :recurrence_rules, :starts_on)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/show.html.erb
<%= link_to "Create group", new_group_path, data: { role: "create-group" } %>

<ul>
  <% @groups.each do |group| %>
    <%= content_tag_for(:li, group) do %>
      <%= link_to group.title, group %>
    <% end %>
  <% end %>
</ul>

app/views/groups/new.html.erb
<%= form_for @group do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.submit "Create" %>
  </div>
<% end %>

app/views/groups/show.html.erb
<h1><%= @group.title %></h1>

<ul class="members">
  <% @group.members.each do |member| %>
    <li class="member"><%= member.username %></li>
  <% end %>
</ul>

<%= link_to "Add location", new_group_location_path(@group), data: { role: "add-location" } %>

<ul class="locations">
  <% @group.locations.each do |location| %>
    <li class="location"><%= link_to location.name, [@group, location] %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boardgamenight</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <header>
      <% if signed_in? %>
        <%= link_to 'Dashboard', dashboard_path %>
        <%= link_to "Sign out", session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign in", new_session_path %>
      <% end %>
    </header>


    <%= yield %>

  </body>
</html>

app/views/locations/new.html.erb
<%= form_for [@group, @location] do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit "Add location" %>
  </div>
<% end %>

app/views/locations/show.html.erb
<%= form_for [@group, @location] do |form| %>
  <div>
    <%= form.label :starts_on %>
    <%= form.date_field :starts_on %>
  </div>
  <div>
    <%= form.label :recurrence_rules, "When" %>
    <%= form.select_recurring :recurrence_rules %>
  </div>
  <div>
    <%= form.submit "Update Schedule" %>
  </div>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>